language: node_js
node_js:
  - "6.9.5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --tags
  - node --version
  - npm install -g yarn

script: bash ./scripts/build.sh
env:
  global:
  - ENCRYPTION_LABEL: "9290ac03541c"
